insta/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.index, name="index")
]

insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include

# from .views import HomeView

urlpatterns = [
    path('', include('api.urls')),  # 새로만들어준 app의 url 기본 path설정해주기
    path('member/', include('member.urls')),
    path('admin/', admin.site.urls, name="admin"),
    path('rest-auth/', include('rest_auth.urls')),
    path('photo/', include('photo.urls')),

    # path('member/', views.index)
]

insta/photo/urls.py
from django.urls import path
from .views import PhotoCreate, PhotoList, PhotoUpdate, PhotoDelete, PhotoSearchView

from django.conf.urls.static import static
from django.conf import settings

app_name = 'photo'

urlpatterns = [
    path("", PhotoList.as_view(), name='index'),
    path("create/", PhotoCreate.as_view(), name='create'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("search/", PhotoSearchView.as_view(), name='search'),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/photo/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Photo(models.Model):
    text = models.TextField(blank=True)
    img = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created']

insta/photo/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word  ')

insta/photo/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .forms import PostSearchForm

# Create your views here.
from django.views.generic.list import ListView
from django.views.generic import CreateView, UpdateView, DeleteView, FormView

from .models import Photo


class PhotoCreate(CreateView):
    model = Photo
    fields = ['text', 'img']
    template_name_suffix = '_create'
    success_url = '/photo'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.save()
        return redirect('/photo')


class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'


class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['text', 'img']
    template_name_suffix = '_update'
    success_url = '/photo'


class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/photo'


class PhotoSearchView(FormView):
    form_class = PostSearchForm
    template_name = 'photo/photo_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        photo_list = Photo.objects.filter(Q(text__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = photo_list

        return render(self.request, self.template_name, context)

insta/photo/templates/photo/photo_create.html
{% extends 'home/base.html' %}

{% block content %}

<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>

{% endblock %}

insta/photo/templates/photo/photo_delete.html
{% extends 'home/base.html' %}

{% block content %}
<div class="alert alert-primary" role="alert">정말로 삭제하시겠습니까?</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
{% endblock %}

insta/photo/templates/photo/photo_list.html
{% extends 'home/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-5">
            {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                    <p class="card-text">{{ object.user }}</p>
                </div>
                <img src="{{ object.img.url }}" class="card-img-top" alt="...">

                <div class="card-body">
                    <p class="card-text">{{ object.text }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">올린 날짜 : {{ object.created }}</li>
                </ul>
                <ul>
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                </ul>
            </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

insta/photo/templates/photo/photo_search.html
{% extends "home/base.html" %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>
    <br><br>
    
    {% if object_list %}
        {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                </div>
                <img src="{{ object.img.url }}" class="card-img-top" alt="...">

                <div class="card-body">
                    <p class="card-text">{{ object.text }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">올린 날짜 : {{ object.created }}</li>
                </ul>
            </div>

            {% endfor %}
    {% elif search_term %}
        <b><i>Search Word ({{ search_term }}) Not Found</i></b>
    {% endif %} 
{% endblock %}

insta/photo/templates/photo/photo_update.html
{% extends 'home/base.html' %}
{% block content %}

<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
    <div class="col"></div>
</div>

{% endblock %}